# Basic Site Settings
title: "Khaled Hashem - Markiting student"
description: "Portfolio and Strategic Marketing Blog"
url: "https://khaled-wal.github.io/" 
baseurl: "" # اتركه فارغاً إذا كان الموقع على الرابط الرئيسي، أو ضع اسم المستودع إذا كان فرعياً مثل "/portfolio"

# Resume Link
cv_link: "/assets/files/KhaledWaleedCV.pdf"

# Default Language & Direction (English Base)
lang: "en"
dir: "ltr"

# Collections for Portfolio/Case Studies
collections:
  case_studies:
    output: true
    permalink: /portfolio/:title/